name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: VanillaPlusAdditions v${{ env.VERSION }}
          body: |
            ## VanillaPlusAdditions v${{ env.VERSION }}
            
            ### 🚀 Installation
            1. Download the jar file
            2. Place it in your mods folder
            3. Make sure you have NeoForge for Minecraft 1.21 installed
            
            ### 📦 Modules
            - **Hostile Zombified Piglins**: Enhanced Nether difficulty
            - **Wither Skeleton Enforcer**: No normal skeletons in Nether
            - **MobGlow Command**: Visualize and track entities
            
            ### 🔧 Configuration
            See [Configuration Guide](https://github.com/Gerry3010/vanillaplusadditions/blob/master/MODULE_CONFIG_GUIDE.md)
            
            ### 🐛 Debug Logging
            See [Debug Logging Guide](https://github.com/Gerry3010/vanillaplusadditions/blob/master/DEBUG_LOGGING_CONFIG.md)
          files: |
            build/libs/*.jar
          draft: false
          prerelease: false

      - name: Upload to CurseForge
        if: false  # Disabled until CurseForge API key is configured
        uses: gradle/gradle-build-action@v2
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        with:
          arguments: curseforge